parent=keycloak
import=common/keycloak
styles=css/login.css css/impactc.css
locales=fr,en
kcHtmlClass=impactc-html
kcBodyClass=impactc-body
kcHeaderWrapperClass=impactc-header-wrapper
kcHeaderClass=impactc-header
kcFormCardClass=impactc-card
kcFormCardAccountClass=impactc-card
kcFormHeaderClass=impactc-card-header
kcFormGroupClass=impactc-form-group
kcLabelClass=impactc-label
kcInputClass=impactc-input
kcInputWrapperClass=impactc-input-wrapper
kcButtonClass=impactc-button
kcButtonPrimaryClass=impactc-button-primary
kcButtonDefaultClass=impactc-button-secondary
kcFormOptionsClass=impactc-form-options
kcFormOptionsWrapperClass=impactc-form-options-wrapper
kcFormSettingClass=impactc-form-setting
kcInfoAreaWrapperClass=impactc-info-area
kcAlertClass=impactc-alert
kcAlertTitleClass=impactc-alert-title
kcFeedbackErrorIcon=pficon pficon-error-circle-o
