apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: optimizesolux-common
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - redis.yaml
  - keycloak.yaml
  - core-apps.yaml
  - observability.yaml
  - mesh.yaml
